# Generated by Django 5.1.2 on 2024-10-13 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_remove_candidate_email_remove_candidate_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvdata',
            name='cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_data', to='candidates.cv'),
        ),
    ]
