# Generated by Django 5.1.2 on 2024-10-16 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_candidate_is_scraping_candidate_last_scrape_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('on-site', 'On-site')], max_length=50, null=True),
        ),
    ]
