# Generated by Django 5.1.2 on 2024-11-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0010_job_salary_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(default='reference', max_length=255)),
                ('template', models.CharField(default='sydney', max_length=255)),
                ('company_logo', models.JSONField(default=dict)),
                ('page', models.JSONField(default=dict)),
                ('certifications', models.JSONField(default=dict)),
                ('education', models.JSONField(default=dict)),
                ('experience', models.JSONField(default=dict)),
                ('volunteering', models.JSONField(default=dict)),
                ('interests', models.JSONField(default=dict)),
                ('languages', models.JSONField(default=dict)),
                ('projects', models.JSONField(default=dict)),
                ('references', models.JSONField(default=dict)),
                ('skills', models.JSONField(default=dict)),
                ('social', models.JSONField(default=dict)),
                ('theme', models.JSONField(default=dict)),
                ('personnel', models.JSONField(default=dict)),
                ('typography', models.JSONField(default=dict)),
            ],
        ),
    ]
