# Generated by Django 5.1.2 on 2024-11-09 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0011_modele'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='generated_html',
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'French')], default='en', max_length=10)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('templateData', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='candidates.modele')),
            ],
        ),
        migrations.AddField(
            model_name='cv',
            name='template',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidates.template'),
        ),
    ]
