# Generated by Django 5.1.2 on 2024-11-25 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0016_cvdata_yoe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, unique=True)),
                ('is_scraped', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100, unique=True)),
                ('is_scraped', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_jobs_to_scrape', models.IntegerField(default=100)),
                ('is_scraping', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='KeywordLocationCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_scraped', models.BooleanField(default=False)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.keyword')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.location')),
            ],
            options={
                'unique_together': {('keyword', 'location')},
            },
        ),
    ]
