# Generated by Django 5.1.2 on 2024-11-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0018_pack_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(max_length=100, unique=True)),
                ('credit_cost', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
