# Generated by Django 5.1.2 on 2024-11-25 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0019_creditaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='cv_type',
            field=models.CharField(choices=[('base', 'Base CV'), ('tailored', 'Tailored CV')], default='base', max_length=10),
        ),
        migrations.AddField(
            model_name='cv',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tailored_cvs', to='candidates.job'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to='candidates.candidate'),
        ),
        migrations.AlterField(
            model_name='cvdata',
            name='cv',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cv_data', to='candidates.cv'),
        ),
    ]
