# Generated by Django 5.1.2 on 2024-12-03 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0021_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='is_scraping',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='last_scrape_time',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='num_jobs_to_scrape',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='scrape_interval',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='scrape_unit',
        ),
    ]
