# Generated by Django 5.1.2 on 2024-12-07 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0022_remove_candidate_is_scraping_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'French')], default='en', max_length=10)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='template',
            name='language',
        ),
        migrations.RemoveField(
            model_name='template',
            name='name',
        ),
        migrations.RemoveField(
            model_name='template',
            name='reference',
        ),
        migrations.AddField(
            model_name='template',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='template_thumbnails/'),
        ),
        migrations.AddField(
            model_name='template',
            name='abstract_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='candidates.abstracttemplate'),
        ),
    ]
