# Generated by Django 5.1.2 on 2024-12-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0023_abstracttemplate_remove_template_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstracttemplate',
            name='language',
        ),
        migrations.AddField(
            model_name='template',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French')], default='en', max_length=10),
        ),
    ]
