# Generated by Django 5.1.2 on 2024-12-09 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0026_remove_cv_template_template_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='cv',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template', to='candidates.cv'),
        ),
    ]
