# Generated by Django 5.1.2 on 2024-12-09 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0028_alter_template_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='cv',
        ),
        migrations.AddField(
            model_name='cv',
            name='template',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidates.template'),
        ),
    ]
