# Generated by Django 5.1.2 on 2024-12-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0029_remove_template_cv_cv_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='cv',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='cv_thumbnails/'),
        ),
    ]
