# Generated by Django 5.1.2 on 2024-12-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0030_remove_template_thumbnail_cv_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstracttemplate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='template_images/'),
        ),
    ]
