# Generated by Django 5.1.2 on 2024-12-15 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0031_abstracttemplate_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='original_url',
            field=models.CharField(max_length=1000),
        ),
    ]
