# Generated by Django 5.1.2 on 2024-12-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0034_alter_cv_generated_pdf_alter_cv_original_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='industry',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='original_url',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_range',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
