# Generated by Django 5.1.2 on 2025-01-01 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0036_job_company_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsearch',
            name='status',
        ),
        migrations.AddField(
            model_name='jobsearch',
            name='is_applied',
            field=models.BooleanField(default=False),
        ),
    ]
