# Generated by Django 5.1.2 on 2025-01-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0039_ad_alter_candidate_phone_alter_cvdata_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ads_per_page', models.PositiveIntegerField(default=2, help_text='Number of ads to display per page.')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
