# Generated by Django 5.1.2 on 2025-01-11 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0040_generalsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='max_recent_search_terms',
            field=models.PositiveIntegerField(default=10, help_text='Number of search suggestions to display.'),
        ),
        migrations.CreateModel(
            name='SearchTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_searched_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_terms', to='candidates.candidate')),
            ],
        ),
    ]
