# Generated by Django 5.1.2 on 2025-01-11 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0041_candidate_profile_picture_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeneralSettings',
            new_name='GeneralSetting',
        ),
        migrations.RenameModel(
            old_name='ScrapingSettings',
            new_name='ScrapingSetting',
        ),
    ]
