# Generated by Django 5.1.2 on 2025-01-17 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0043_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='ad_type',
            field=models.CharField(choices=[('in_top', 'In Top'), ('in_jobs', 'In Jobs'), ('in_loading', 'In Loading')], default='in_jobs', max_length=20),
        ),
    ]
