# Generated by Django 5.1.2 on 2025-01-20 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0044_ad_ad_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsearch',
            name='candidate',
        ),
        migrations.AddField(
            model_name='jobsearch',
            name='cv',
            field=models.ForeignKey(default=235, on_delete=django.db.models.deletion.CASCADE, related_name='job_searches', to='candidates.cv'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobsearch',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_searches', to='candidates.job'),
        ),
    ]
